"""Tool wrapper functions for SheetAgent action executors.

This module provides LangChain tool wrappers for the SheetAgent action executors.
Each function is decorated with @tool and provides a clear interface for the LLM
to interact with the underlying ActionExecutor classes.
"""
import logging
import re
from typing import Annotated
from langchain_core.tools import tool, InjectedToolCallId
from langchain_core.messages import ToolMessage
from langgraph.prebuilt import InjectedState
from langgraph.types import Command
from pathlib import Path

from app.graph.state import GraphState
from app.core.actions import PythonInterpreter, SheetSelector, AnswerSubmitter
from app.utils.types import TableRepType

logger = logging.getLogger(__name__)

@tool("python_executor", parse_docstring=True)
def python_executor(
    code: str,
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[GraphState, InjectedState],
) -> dict:
    """Execute Python code in a sandboxed environment.

    This tool allows you to execute Python code to analyze, manipulate, and visualize
    data in the workbook.

    Args:
        code: The Python code to execute.
    """
    sandbox = state["sandbox"]
    executor = PythonInterpreter(sandbox)
    previous_sheet_state = state["current_sheet_state"]
    response = executor.utilize(code)
    current_sheet_state = sandbox.get_sheet_state()

    return Command(
        update={
            "current_sheet_state": current_sheet_state,
            "previous_sheet_state": previous_sheet_state,
            "messages": [
                ToolMessage(
                    content=response.obs,
                    tool_call_id=tool_call_id,
                    name="python_executor",
                )
            ],
        }
    )

@tool(name_or_callable="cell_range_reader")
def cell_range_reader(
    sheet_name: str,
    cell_range: str,
    state: Annotated[GraphState, InjectedState]
) -> str:
    """Read the values from a specific sheet and cell range.
    
    This tool allows you to read the values of cells from a specific sheet and cell range.
    
    Args:
        sheet_name: The name of the sheet to read
        cell_range: The cell range to read (e.g. "A1:B2")
        state: The current state of the graph (automatically provided)
    
    Returns:
        The data from the sheet and cell range
    """
    # Check that the range is valid
    if not cell_range:
        return "Error: Cell range is empty"
    
    if not sheet_name:
        return "Error: Sheet name is empty"
    
    # Check the format to be A1:B2
    if not re.match(r'^[A-Z]+\d+:[A-Z]+\d+$', cell_range):
        return "Error: Invalid cell range format. Provide a valid cell range in the format A1:B2."
        
    sandbox = state["sandbox"]
    executor = PythonInterpreter(sandbox)
    code = f"""
sheet = workbook["{sheet_name}"]
rows = sheet["{cell_range}"]
if len(rows) == 0:
    print("Error: The cell range is empty. Please provide a valid cell range.")
    return

if len(rows) > 10:
    print("Error: The cell range is too large. Please provide a cell range with a maximum of 10 rows and 10 columns.")
    return

if len(rows[0]) > 10:
    print("Error: The cell range is too large. Please provide a cell range with a maximum of 10 rows and 10 columns.")
    return

for row in sheet["{cell_range}"]:
    for cell in row:
        print(cell.row, cell.column, cell.value)
"""

    response = executor.utilize(code)
    return response.obs

@tool("get_row_types")
def get_row_types(
    sheet_name: str,
    invoice_amount_column: str,
    tool_call_id: Annotated[str, InjectedToolCallId],
    state: Annotated[GraphState, InjectedState],
) -> dict:
    """
    Analyzes a sheet to classify rows into 'invoice', 'credit', and 'cumulative'.

    This should be the FIRST tool you call to understand the sheet's structure.
    It identifies rows based on the value in the invoice amount column.
    - 'invoice' rows have a POSITIVE invoice amount.
    - 'credit' rows have a NEGATIVE invoice amount.
    - 'cumulative' rows are totals or other non-data rows, often with empty or non-numeric values in key columns.

    Args:
        sheet_name: The name of the sheet to analyze (e.g., 'Sheet1').
        invoice_amount_column: The column letter containing the invoice amounts (e.g., 'F').

    Returns:
        A JSON object with three keys: 'invoice_rows', 'credit_rows', and 'cumulative_rows',
        each containing a list of corresponding row numbers.
    """
    sandbox = state["sandbox"]
    executor = PythonInterpreter(sandbox)

    # Python code to be executed in the sandbox.
    # This is deterministic and not generated by the LLM.
    code = f"""
import json
import pandas as pd

# Use pandas for robust data reading from openpyxl sheet
ws = workbook["{sheet_name}"]
data = ws.values
cols = next(data) # get headers
data = list(data)
df = pd.DataFrame(data, columns=cols)

# Ensure the row numbers align with Excel's 1-based indexing + header
df.index = df.index + 2

# Find the actual column name from the letter provided
col_index = ord('{invoice_amount_column}'.upper()) - 65
if col_index < 0 or col_index >= len(df.columns):
    print(json.dumps({{"error": "Invalid column letter provided."}}))
else:
    invoice_col_name = df.columns[col_index]

    # Attempt to convert the amount column to numeric, coercing errors to NaN
    # This is a robust way to handle non-numeric/empty cells in cumulative rows
    numeric_amounts = pd.to_numeric(df[invoice_col_name], errors='coerce')

    # Classify rows
    cumulative_rows = df[numeric_amounts.isna()].index.tolist()
    invoice_rows = df[numeric_amounts > 0].index.tolist()
    credit_rows = df[numeric_amounts < 0].index.tolist()

    result = {{
        "invoice_rows": invoice_rows,
        "credit_rows": credit_rows,
        "cumulative_rows": cumulative_rows,
    }}
    print(json.dumps(result))

"""
    # Execute the code in the sandbox
    response = executor.utilize(code)

    return Command(
        update={
            "messages": [
                ToolMessage(
                    content=response.obs,
                    tool_call_id=tool_call_id,
                    name="get_row_types",
                )
            ],
        }
    )
